x-fvnli-bot: &fvnli-bot
  image: ghcr.io/akibaat/fvn.li-discord-bot:development

services:
  bot:
    <<: *fvnli-bot
    restart: unless-stopped
    networks:
      - fvnli
    environment:
      - DISCORD_API_KEY
      - DISCORD_ADMIN_ID
      - DISCORD_ADMIN_NOTIFICATIONS_CHANNEL_ID
      - DISCORD_DEV_MODE
      - DISCORD_DEV_USER_IDS
      - DISCORD_DEV_GUILD_IDS
      - LARAVEL_API_URL
      - LARAVEL_API_TOKEN

networks:
  fvnli:
    name: ${COMPOSE_NETWORK_NAME}
    external: true
